version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nota-parser-api
    container_name: nota-parser-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
